GET http://localhost:3030/rooms

###

POST http://localhost:3030/rooms/create
Content-Type: application/json

{
    "name": "witam",
    "password": "serdecznie"
}

###

POST http://localhost:3030/rooms/join
Content-Type: application/json

{
    "_id": "5fb4138f92dda52b082ec367",
    "password": "serdecznie"
}